### ISSUE TITLE
SoftmaxRegression - zero_init_weight missing

### ISSUE THREAD

**Issue by theiling** [rasbt/python-machine-learning-book#10] opened 2016-06-04 16:42 UTC
Hello,
I think the function  zero_init_weight is missing.
I searched the github site but did not find it.
Maybe this is another version of the softmax-regressor and here it is missing?

Best Regards, Thomas

**Comment by rasbt** [comment] 2016-06-06 00:11
Thanks for the heads-up, Thomas, it should be fixed now! The `zero_init_weight` was a left-over from te logistic regression implementation (which I used as a template). In practice, it's better to initialize the weights with small, random and normal distributed values, which is why I decided to remove that parameter (also, I renamed it to init_params to be less ambiguous, since we work with `weights` and the `bias` parameters separately in this implementation).

**Closed by rasbt** 2016-06-06 00:11 UTC
